### ISSUE TITLE
Flutter SDK

### ISSUE THREAD

**Issue by Urkman** [TelemetryDeck/Issues#190] opened 2022-04-27 08:34 UTC
Any plans on a Flutter SDK?

**Comment by winsmith** [comment] 2022-04-27 10:12
Not right now, but leave this ticket open, and I'll add it to the roadmap :)

**Comment by FantaMagier** [comment] 2023-05-30 06:35
Flutter SDK would be great!

**Comment by Flajt** [comment] 2023-10-09 21:09
Hello, I might take this on, since I need an analytics service until I manage to build my own. 

I can't guarante it tho, since it would be part of a project I'm working on right now and the timeline could be to narrow.
I would give a heads up here if I manage to work on it.

**Comment by winsmith** [comment] 2023-10-12 07:13
Sure, that'd be lovely!

**Comment by Flajt** [comment] 2023-10-15 12:23
I've done a bit of reading up on stuff (would be my first plugin with native interactions). My original idea was to wrap your existing kotlin and swift clients with platform channels and dart code. But there is a small issue: You've used only spm and not cocoapods for distribution right?


Flutter currently seems to support only cocoapods. flutter/flutter#33850
Which would leave me with 4 options:

- Try a [workaround](https://github.com/flutter/flutter/issues/33850#issuecomment-1440675944) where the user still needs to add the swift package to their app (and idk if it works sice I didnt touch native code so far) 
- write everything in dart (however then there would be three codebases that need to be in sync)
- You add support for cocoapods (an [article](https://medium.com/clutter-engineering/supporting-both-swift-package-manager-and-cocoapods-in-your-library-861f00b6b0f9) I found in regards to that)
- I wait until the issue is resolved by flutter flutter/flutter#126005 

EDIT: Add relevant issues

**Comment by winsmith** [comment] 2023-10-16 08:52
Thanks a lot for researching this! I think we could add support for cocoapods. So far, I didn't want to support it mostly because it's increasingly unnecessary for modern iOS projects and would add additional support load. But with this added benefit, it might just push that balance over to "let's support it". 

What do you think?

**Comment by Flajt** [comment] 2023-10-16 09:10
If possible that would be nice, and the good thing is you could remove it as soon as flutter adds support for spm.

Otherwise I would attempt to write it purely in dart.

**Comment by Flajt** [comment] 2023-11-20 16:35
Just jumping in to give a small heads up: I think I would be able to start working on it next week or the week afterwards, if the SPM related implementations are added. If that would be too soon, you can just give me a heads up when you have managed to implement it and I will attempt it then.

**Comment by winsmith** [comment] 2024-01-03 10:26
Heads up: we're starting work on cocoapods support internally. It's time to get this show on the road!

**Comment by Flajt** [comment] 2024-02-03 11:21
Seems like it has been added, I will start working on it when I find the time (I'm currently starting to get a bit busy). I will update you how it goes.

Edit:

I've tried myself on the SwiftClient, in theory doable, but there seem to be one or two major issues. But as soon as I figure this out it should be done in no time.

**Comment by Flajt** [comment] 2024-02-04 23:00
iOS seems to work now. (There was a weird issue that was resolved after rerunning the creation process 5 times). 

The repo is: flajt/flutter_telemetrydeck

Will aim for kotlin next.

**Comment by winsmith** [comment] 2024-02-05 16:51
I'm sorry we've already received a finished Flutter SDK recently, so your work might be duplicate. But on the good side, we'll release it this week or so, so you'll be able to use it very soon.

**Closed by winsmith** 2024-02-05 16:51 UTC
Labels: Requested

**Comment by Flajt** [comment] 2024-02-05 16:57
Np, I will delete my version to prevent confusion.
